const SEARCH_PLACEHOLDER_TEXT = 'Which city are you visiting?'

const LOADING_RESULTS = 'Hang on for a sec while we gather places to go to...';

const GO_BUTTON_TEXT = 'GO';
const PLACES_BUTTON_TEXT = 'PLACES';
const ADD_TO_ROUTE_TEXT = 'ADD TO ROUTE';
const REMOVE_FROM_ROUTE_TEXT = 'REMOVE FROM ROUTE';
const ROUTES_BUTTON_TEXT = 'ROUTE';
const SAVE_BUTTON_TEXT = 'SAVE';
const SETTINGS_BUTTON_TEXT = 'SETTINGS';


module.exports = {
	SEARCH_PLACEHOLDER_TEXT,
	LOADING_RESULTS,
	GO_BUTTON_TEXT,
	PLACES_BUTTON_TEXT,
	ADD_TO_ROUTE_TEXT,
	REMOVE_FROM_ROUTE_TEXT,
	ROUTES_BUTTON_TEXT,
	SAVE_BUTTON_TEXT,
	SETTINGS_BUTTON_TEXT
};